version: "3"

volumes:
  dbdata:
    external: true
    
services:

  backend:

    container_name: backend_app
    restart: always
    build:
      context: ./backend
    command: gunicorn backend.wsgi
    ports:
      - "8000:8000"

  db:

    container_name: postgresql_container
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
