# Generated by Django 3.2 on 2022-01-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('total_cases', models.IntegerField(blank=True, default=0, null=True)),
                ('new_cases', models.IntegerField(blank=True, default=0, null=True)),
                ('total_deaths', models.IntegerField(blank=True, default=0, null=True)),
                ('new_deaths', models.IntegerField(blank=True, default=0, null=True)),
                ('total_recovered', models.IntegerField(blank=True, default=0, null=True)),
                ('new_recovered', models.IntegerField(blank=True, default=0, null=True)),
                ('active_cases', models.IntegerField(blank=True, default=0, null=True)),
                ('serious_critical', models.IntegerField(blank=True, default=0, null=True)),
                ('population', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
